### ISSUE TITLE
if i try to install it all goes blank

### ISSUE THREAD

**Issue by SiteHelp** [o0johntam0o/phpBB-Extension-Archive#4]
when i try to install this all goes blank to white page, aswell admin as site part

**Comment by o0johntam0o** [comment]
What version of phpBB you're working on?

**Comment by SiteHelp** [comment]
3.1.7pl

**Comment by SiteHelp** [comment]
i updated mine php on mine server and i am running php 7.0.3 now and it all works now
so the empty pages was related to older php version, i ran before this php 5.3

**Comment by o0johntam0o** [comment]
Yes SiteHelp, Codebox Plus requires PHP version >=5.3.3
